OBJS = bin/main.o bin/functions.o bin/material.o
CXXFLAGS = -Wall -std=c++11 `wx-config --cxxflags` -I "include/"
LDLIBS   = `wx-config --libs`

learning: $(OBJS)
	g++ -o learning $(OBJS) $(CXXFLAGS) $(LDLIBS)  

bin/main.o: src/main.cpp 
	g++ src/main.cpp -c -o bin/main.o $(CXXFLAGS)

bin/functions.o: src/functions.cpp
	g++ src/functions.cpp -c -o bin/functions.o $(CXXFLAGS)

bin/material.o: src/material.cpp
	g++ src/material.cpp -c -o bin/material.o $(CXXFLAGS)

clean:
	rm bin/*.o
	rm learning

run: learning

	./learning
